server:
  port: 8091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 114.55.36.227
  rabbitmq:
    host: 114.55.36.227
    port: 5672
    virtual-host: /
    username: guest
    password: guest


gmall:
  jwt:
    pubKeyPath: C:\\Users\\kaixuan\\Desktop\\gmall_cloud\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
  main:
    pool:
      corePoolSize: 8
      maximumPoolSize: 100
      keepAliveTime: 10
      queueSize: 10000
  other:
    pool:
      corePoolSize: 8
      maximumPoolSize: 100
      keepAliveTime: 10
      queueSize: 10000
feign:
  client:
    config:
      default:
        readTimeout: 60000

alipay:
  app_id: 2016101400684042
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCX1oq4n1xaUY3w1XL0bfHVHa5r0LlPtpO+Bj4iYRu24kSsZ/45uXL+rKFPGDL5HPEEjw8rk6hskZhJ2xJFJkdfyhjx56Z+JfsJVNJRB7CkfjCnuUYAoeL56ibulL+ZBNAqhfXIWexCAsON6KZ7VrbHsHuVK18Y4QcIo7DFmu6VutnZ7iprHj/A51TYuuCGTvf/IHkK1da5KIlr4hyTEG4EXx0VUSx8FQ9grrsFGrgw+TmsUlY3LcfNOmPXFF/0SjCNIyXJ6u/HFrm9S7zyhAAdCf2Xh0L2yjJWvAWMhlr9lpf8pQv42d3HnW1hyVLO9qUZ3zeaKzEq0yiESPK1eRxdAgMBAAECggEBAJXOYseM0315AWYf8m8fGn597l0JbgwrwtC1MBCTZtilncPMRpOFWOPURsLWyVPnLhSlYP5JjN6xN2OG9RusjLcBmmLxft7vciLewTKZN7rTlgWlUl/FWT/huc+iivbaPNf3m2u07NikCXS1mawO/f8/LG8cf5L4UgxAFGSiW8r1KGfJY9m6axNIex53CSiKgzH4vkmsut5FOA5DXQ2ceQsQ8QzsXY9/fEThwtIMZCShadnWPYRMIOLgi+4H4ytdZrcJe9WCZ9yyOE734b6MygmKU8ArE93XBnCFxQexvbZVJl5FeMHjaNA0nyW6Rzt9uTe31WoBtzPzpDuIqtwhsoECgYEA6y5rCRviNCXOwaLtI42tv7LZfatgYmoi2YhyU1s1OsU5HqzaBnlpv3+q4ft9GlALy/6bM4BugiozYXMPjxecrwrzHy6kyBCiBB+Wi12jNEchZVRP66OmKafbo7C2KD+B+3mOFaNStzPwBZjRtjhVN5N4fYNZNDG9atl30HjBKFUCgYEApUdu4F3j7UWYcl56xXINCX+m1yEExjA0JIcUVPUNE0ImR0Poo+GE1G45A0JIT8is4lWlr6Z58z4UJIY+G7WLBW0n28nC/YLyXprG+bdH/FmW0ypHLXsJqivsEEcw3BmGqhYePDE2uKftQvCJlyY/6ybWrATVTyCJ5vj7tYfwy+kCgYBs7C20pU5p2ozcz+nGyqqLG3lxo7rbOc70MybIBnkrxAZFd8busrLQd3+cdE6nriUYkM4u1y/XZ1YurwyouEXgKFEbww2cf1+aS0r9NxwMbVlBRgBR4ZRmvJCUSpbDI06/Orgcu2zm3s4uuW1/WK3XNJzcfMYGz3asExZT3mmPlQKBgD9/NA+qwpgzdp/pwEz+xhdyHUzk+IqTllS6OItzIbTWYxJZ+pSLXZanSewAmPtd412I/gB/eraCkQZ/NHk8w84v43JDD1CJ8Ed8OxlQ2q0OVi2GPpYwgMQJ38VZNGI6xEuv96m0VouWqEZhVtrk7QWQhETODo05uQEtgrZ5JX+RAoGBAJe4TVAFZ+OvZJCr7sePExJPaIOALggCJtl114/k5JDhh76/gs7tIsFXCgEkvo9ISS2K7wljd4tkG8NXYSLOoSIYddwN6q8BjYZSwbulKYaFjj9GCs4E4wvxIuHed3n/vhG8wjJSuUAVDRuQeotqXGcAkrrJdxlwont84GD0xwrh
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9aKuJ9cWlGN8NVy9G3x1R2ua9C5T7aTvgY+ImEbtuJErGf+Obly/qyhTxgy+RzxBI8PK5OobJGYSdsSRSZHX8oY8eemfiX7CVTSUQewpH4wp7lGAKHi+eom7pS/mQTQKoX1yFnsQgLDjeime1a2x7B7lStfGOEHCKOwxZrulbrZ2e4qax4/wOdU2Lrghk73/yB5CtXWuSiJa+IckxBuBF8dFVEsfBUPYK67BRq4MPk5rFJWNy3HzTpj1xRf9EowjSMlyervxxa5vUu88oQAHQn9l4dC9soyVrwFjIZa/ZaX/KUL+Nndx51tYclSzvalGd83misxKtMohEjytXkcXQIDAQAB
  notify_url:
  return_url:
  gatewayUrl: https://openapi.alipaydev.com/gateway.do