server:
  port: 8088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



gmall:
  main:
    pool:
     corePoolSize: 8
     maximumPoolSize: 100
     keepAliveTime: 10
     queueSize: 10000
  other:
    pool:
      corePoolSize: 8
      maximumPoolSize: 100
      keepAliveTime: 10
      queueSize: 10000